---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ultra_collection_namespace.ultra_collection
  tags:
    - ansible
    - playbook
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ultraJeffOrg/cron-playbook
  links:
    - url: https://devspaces.apps.tallgeese.ultra.lab/#https://github.com/ultraJeffOrg/cron-playbook
      title: Open in Dev Spaces
      icon: catalog
      type: ide
spec:
  type: playbook-project
  system: system:default/utilities
  lifecycle: production
  owner: user:default/admin
